[server]
port = 5555

[node]
detect-drivers = false

[relay]
url = "http://samsung:4723/wd/hub"
status-endpoint = "/status"
configs = [
  "1", "{\"browserName\": \"chrome\", \"platformName\": \"android\", \"appium:platformVersion\": \"13.0\"}"
]

